### ISSUE TITLE
gitifnore => .gitignore

### ISSUE THREAD

**Issue by luxus1337** [heyanton/simple_webpack_boilerplate#1]
The article (https://dev.to/pixelgoo/how-to-configure-webpack-from-scratch-for-a-basic-website-46a5) helped me out and hit the nail on the head. However there is one minor disturbance in the force.

`.gitifnore` => `.gitignore`

And so you have a source controlled node_modules in the repo :).. otherwise cheers!

**Comment by antmelnyk** [comment]
Ah, such a typo! Thanks for notice!

Fixed 4226671964ebcb31c200da199072f8f4c3aa6ddd
